In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import nltk
from os import getcwd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, classification_report

In [5]:
import warnings
warnings.filterwarnings('ignore')

In [32]:
!pip install python-utils

Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for python-utils from https://files.pythonhosted.org/packages/26/45/98431ba6d17b99468bd3f4c53fdeefff402167f006a06773905296f6d489/python_utils-3.8.2-py2.py3-none-any.whl.metadata



[notice] A new release of pip is available: 23.2.1 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [36]:
!pip install pygod

Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for pygod from https://files.pythonhosted.org/packages/61/f7/1a7d1f5e621475fb70d6d284fc3c432df6702bf59d86e8c61fa7d14e02d7/pygod-1.1.0-py3-none-any.whl.metadata
  Obtaining dependency information for networkx from https://files.pythonhosted.org/packages/38/e9/5f72929373e1a0e8d142a130f3f97e6ff920070f87f91c4e13e40e0fba5a/networkx-3.3-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/86.8 kB ? eta -:--:--
   ---- ----------------------------------- 10.2/86.8 kB ? eta -:--:--
   ------------------ --------------------- 41.0/86.8 kB 326.8 kB/s eta 0:00:01
   ------------------ --------------------- 41.0/86.8 kB 326.8 kB/s eta 0:00:01
   ---------------------------- ----------- 61.4/86.8 kB 328.2 kB/s eta 0:00:01
   ---------------------------- ----------- 61.4/86.8 kB 328.2 kB/s eta 0:00:01
   ---------------------------- ----------- 61.4/86.8 kB 328.2 kB/s


[notice] A new release of pip is available: 23.2.1 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [48]:
!pip install torch

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 23.2.1 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [49]:
%pip install torch

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [50]:
!pip install ultralytics

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 23.2.1 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [23]:
!pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 23.2.1 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [25]:
import tensorflow as tf

In [26]:
tf.keras.datasets.mnist.load_data(
    path='blogs.csv')

11490434/11490434 [==============================] - 26s 2us/step


((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [2]:
data = pd.read_csv(r"C:\Users\Admin\Downloads\blogs.csv")
data

Data              Labels
0     Path: cantaloupe.srv.cs.cmu.edu!magnesium.club...         alt.atheism
1     Newsgroups: alt.atheism\nPath: cantaloupe.srv....         alt.atheism
2     Path: cantaloupe.srv.cs.cmu.edu!das-news.harva...         alt.atheism
3     Path: cantaloupe.srv.cs.cmu.edu!magnesium.club...         alt.atheism
4     Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:53...         alt.atheism
...                                                 ...                 ...
1995  Xref: cantaloupe.srv.cs.cmu.edu talk.abortion:...  talk.religion.misc
1996  Xref: cantaloupe.srv.cs.cmu.edu talk.religion....  talk.religion.misc
1997  Xref: cantaloupe.srv.cs.cmu.edu talk.origins:4...  talk.religion.misc
1998  Xref: cantaloupe.srv.cs.cmu.edu talk.religion....  talk.religion.misc
1999  Xref: cantaloupe.srv.cs.cmu.edu sci.skeptic:43...  talk.religion.misc

[2000 rows x 2 columns]

In [59]:
data.shape

(2000, 2)

In [60]:
data.columns

Index(['Data', 'Labels'], dtype='object')

In [61]:
data.head()

Data       Labels
0  Path: cantaloupe.srv.cs.cmu.edu!magnesium.club...  alt.atheism
1  Newsgroups: alt.atheism\nPath: cantaloupe.srv....  alt.atheism
2  Path: cantaloupe.srv.cs.cmu.edu!das-news.harva...  alt.atheism
3  Path: cantaloupe.srv.cs.cmu.edu!magnesium.club...  alt.atheism
4  Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:53...  alt.atheism

In [62]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Data    2000 non-null   object
 1   Labels  2000 non-null   object
dtypes: object(2)
memory usage: 31.4+ KB


In [63]:
data.isnull().sum()

Data      0
Labels    0
dtype: int64

In [40]:
categorical = [var for var in data.columns if data[var].dtype=='O']
print('There are {} categorical variables\n'.format(len(categorical)))
print('The categorical variables are :\n\n', categorical)

There are 2 categorical variables

The categorical variables are :

 ['Data', 'Labels']


In [41]:
data[categorical].head()

Data       Labels
0  Path: cantaloupe.srv.cs.cmu.edu!magnesium.club...  alt.atheism
1  Newsgroups: alt.atheism\nPath: cantaloupe.srv....  alt.atheism
2  Path: cantaloupe.srv.cs.cmu.edu!das-news.harva...  alt.atheism
3  Path: cantaloupe.srv.cs.cmu.edu!magnesium.club...  alt.atheism
4  Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:53...  alt.atheism

In [42]:
data[categorical].isnull().sum()

Data      0
Labels    0
dtype: int64

In [18]:
for var in categorical:   
    print(data[var].value_counts())

Path: cantaloupe.srv.cs.cmu.edu!magnesium.club.cc.cmu.edu!news.sei.cmu.edu!cis.ohio-state.edu!zaphod.mps.ohio-state.edu!howland.reston.ans.net!agate!doc.ic.ac.uk!uknet!mcsun!Germany.EU.net!thoth.mchp.sni.de!horus.ap.mchp.sni.de!D012S658!frank\nFrom: frank@D012S658.uucp (Frank O'Dwyer)\nNewsgroups: alt.atheism\nSubject: Re: islamic genocide\nDate: 23 Apr 1993 23:51:47 GMT\nOrganization: Siemens-Nixdorf AG\nLines: 110\nDistribution: world\nMessage-ID: <1r9vej$5k5@horus.ap.mchp.sni.de>\nReferences: <1r4o8a$6qe@fido.asd.sgi.com> <1r5ubl$bd6@horus.ap.mchp.sni.de> <1r76ek$7uo@fido.asd.sgi.com>\nNNTP-Posting-Host: d012s658.ap.mchp.sni.de\n\nIn article <1r76ek$7uo@fido.asd.sgi.com> livesey@solntze.wpd.sgi.com (Jon Livesey) writes:\n#In article <1r5ubl$bd6@horus.ap.mchp.sni.de>, frank@D012S658.uucp (Frank O'Dwyer) writes:\n#|> In article <1r4o8a$6qe@fido.asd.sgi.com> livesey@solntze.wpd.sgi.com (Jon Livesey) writes:\n#|> #\n#|> #Noting that a particular society, in this case the mainland UK,\n#

In [23]:
for var in categorical:
    print(data[var].value_counts()/np.float64(len(data)))

Path: cantaloupe.srv.cs.cmu.edu!magnesium.club.cc.cmu.edu!news.sei.cmu.edu!cis.ohio-state.edu!zaphod.mps.ohio-state.edu!howland.reston.ans.net!agate!doc.ic.ac.uk!uknet!mcsun!Germany.EU.net!thoth.mchp.sni.de!horus.ap.mchp.sni.de!D012S658!frank\nFrom: frank@D012S658.uucp (Frank O'Dwyer)\nNewsgroups: alt.atheism\nSubject: Re: islamic genocide\nDate: 23 Apr 1993 23:51:47 GMT\nOrganization: Siemens-Nixdorf AG\nLines: 110\nDistribution: world\nMessage-ID: <1r9vej$5k5@horus.ap.mchp.sni.de>\nReferences: <1r4o8a$6qe@fido.asd.sgi.com> <1r5ubl$bd6@horus.ap.mchp.sni.de> <1r76ek$7uo@fido.asd.sgi.com>\nNNTP-Posting-Host: d012s658.ap.mchp.sni.de\n\nIn article <1r76ek$7uo@fido.asd.sgi.com> livesey@solntze.wpd.sgi.com (Jon Livesey) writes:\n#In article <1r5ubl$bd6@horus.ap.mchp.sni.de>, frank@D012S658.uucp (Frank O'Dwyer) writes:\n#|> In article <1r4o8a$6qe@fido.asd.sgi.com> livesey@solntze.wpd.sgi.com (Jon Livesey) writes:\n#|> #\n#|> #Noting that a particular society, in this case the mainland UK,\n#

In [24]:
data.Labels.unique()

array(['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc',
       'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware',
       'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles',
       'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt',
       'sci.electronics', 'sci.med', 'sci.space',
       'soc.religion.christian', 'talk.politics.guns',
       'talk.politics.mideast', 'talk.politics.misc',
       'talk.religion.misc'], dtype=object)

In [25]:
data.Labels.value_counts()

alt.atheism                 100
comp.graphics               100
talk.politics.misc          100
talk.politics.mideast       100
talk.politics.guns          100
soc.religion.christian      100
sci.space                   100
sci.med                     100
sci.electronics             100
sci.crypt                   100
rec.sport.hockey            100
rec.sport.baseball          100
rec.motorcycles             100
rec.autos                   100
misc.forsale                100
comp.windows.x              100
comp.sys.mac.hardware       100
comp.sys.ibm.pc.hardware    100
comp.os.ms-windows.misc     100
talk.religion.misc          100
Name: Labels, dtype: int64

In [26]:
data['Labels'].replace('?', np.NaN, inplace=True)

In [38]:
data.Labels.value_counts()

alt.atheism                 100
comp.graphics               100
talk.politics.misc          100
talk.politics.mideast       100
talk.politics.guns          100
soc.religion.christian      100
sci.space                   100
sci.med                     100
sci.electronics             100
sci.crypt                   100
rec.sport.hockey            100
rec.sport.baseball          100
rec.motorcycles             100
rec.autos                   100
misc.forsale                100
comp.windows.x              100
comp.sys.mac.hardware       100
comp.sys.ibm.pc.hardware    100
comp.os.ms-windows.misc     100
talk.religion.misc          100
Name: Labels, dtype: int64

In [43]:
data[categorical].isnull().sum()

Data      0
Labels    0
dtype: int64

In [44]:
for var in categorical:
    print(var, ' contains ', len(data[var].unique()), ' labels')

Data  contains  2000  labels
Labels  contains  20  labels


In [45]:
numerical = [var for var in data.columns if data[var].dtype!='O']
print('There are {} numerical variables\n'.format(len(numerical)))
print('The numerical variables are :', numerical)

There are 0 numerical variables

The numerical variables are : []


In [46]:
data[numerical].head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [47]:
data[numerical].isnull().sum()

Series([], dtype: float64)

In [48]:
X = data.drop(['Data'], axis=1)
y = data['Data']

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [50]:
X_train.shape, X_test.shape

((1400, 1), (600, 1))

In [51]:
X_train.dtypes

Labels    object
dtype: object

In [52]:
categorical = [col for col in X_train.columns if X_train[col].dtypes == 'O']
categorical

['Labels']

In [53]:
numerical = [col for col in X_train.columns if X_train[col].dtypes != 'O']
numerical

[]

In [54]:
X_train[categorical].isnull().mean()

Labels    0.0
dtype: float64

In [55]:
for col in categorical:
    if X_train[col].isnull().mean()>0:
        print(col, (X_train[col].isnull().mean()))

In [56]:
X_train[categorical].isnull().sum()

Labels    0
dtype: int64

In [57]:
X_test[categorical].isnull().sum()

Labels    0
dtype: int64

In [58]:
X_test.isnull().sum()

Labels    0
dtype: int64

In [59]:
X_train[categorical].head()

Labels
1719  talk.politics.mideast
1702  talk.politics.mideast
1287        sci.electronics
482   comp.sys.mac.hardware
768               rec.autos

In [60]:
!pip install category_encoders

Defaulting to user installation because normal site-packages is not writeable


[notice] A new release of pip is available: 23.2.1 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [61]:
import category_encoders as ce

In [67]:
encoder = ce.OneHotEncoder(cols=['Labels'])
X_train = encoder.fit_transform(X_train)
X_test = encoder.transform(X_test)

In [68]:
X_train.head()

Labels_1  Labels_2  Labels_3  Labels_4  Labels_5  Labels_6  Labels_7  \
1719         1         0         0         0         0         0         0   
1702         1         0         0         0         0         0         0   
1287         0         1         0         0         0         0         0   
482          0         0         1         0         0         0         0   
768          0         0         0         1         0         0         0   

      Labels_8  Labels_9  Labels_10  Labels_11  Labels_12  Labels_13  \
1719         0         0          0          0          0          0   
1702         0         0          0          0          0          0   
1287         0         0          0          0          0          0   
482          0         0          0          0          0          0   
768          0         0          0          0          0          0   

      Labels_14  Labels_15  Labels_16  Labels_17  Labels_18  Labels_19  \
1719          0          0          0          0          0          0   
1702          0          0          0          0          0          0   
1287          0          0          0          0          0          0   
482           0          0          0          0          0          0   
768           0          0          0          0          0          0   

      Labels_20  
1719          0  
1702          0  
1287          0  
482           0  
768           0

In [69]:
X_train.shape

(1400, 20)

In [70]:
X_test.head()

Labels_1  Labels_2  Labels_3  Labels_4  Labels_5  Labels_6  Labels_7  \
405          0         0         1         0         0         0         0   
1190         0         0         0         0         0         0         0   
1132         0         0         0         0         0         0         0   
731          0         0         0         1         0         0         0   
1754         1         0         0         0         0         0         0   

      Labels_8  Labels_9  Labels_10  Labels_11  Labels_12  Labels_13  \
405          0         0          0          0          0          0   
1190         0         0          0          0          0          0   
1132         0         0          0          0          0          0   
731          0         0          0          0          0          0   
1754         0         0          0          0          0          0   

      Labels_14  Labels_15  Labels_16  Labels_17  Labels_18  Labels_19  \
405           0          0          0          0          0          0   
1190          0          0          0          0          1          0   
1132          0          0          0          0          1          0   
731           0          0          0          0          0          0   
1754          0          0          0          0          0          0   

      Labels_20  
405           0  
1190          0  
1132          0  
731           0  
1754          0

In [71]:
cols = X_train.columns

In [72]:
scaler = RobustScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [73]:
X_train = pd.DataFrame(X_train, columns=[cols])

In [74]:
X_test = pd.DataFrame(X_test, columns=[cols])

In [75]:
X_train.head()

Labels_1 Labels_2 Labels_3 Labels_4 Labels_5 Labels_6 Labels_7 Labels_8  \
0      1.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
1      1.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
2      0.0      1.0      0.0      0.0      0.0      0.0      0.0      0.0   
3      0.0      0.0      1.0      0.0      0.0      0.0      0.0      0.0   
4      0.0      0.0      0.0      1.0      0.0      0.0      0.0      0.0   

  Labels_9 Labels_10 Labels_11 Labels_12 Labels_13 Labels_14 Labels_15  \
0      0.0       0.0       0.0       0.0       0.0       0.0       0.0   
1      0.0       0.0       0.0       0.0       0.0       0.0       0.0   
2      0.0       0.0       0.0       0.0       0.0       0.0       0.0   
3      0.0       0.0       0.0       0.0       0.0       0.0       0.0   
4      0.0       0.0       0.0       0.0       0.0       0.0       0.0   

  Labels_16 Labels_17 Labels_18 Labels_19 Labels_20  
0       0.0       0.0       0.0       0.0       0.0  
1       0.0       0.0       0.0       0.0       0.0  
2       0.0       0.0       0.0       0.0       0.0  
3       0.0       0.0       0.0       0.0       0.0  
4       0.0       0.0       0.0       0.0       0.0

In [76]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [77]:
y_pred = gnb.predict(X_test)
y_pred

array(['Newsgroups: comp.sys.mac.hardware\nPath: cantaloupe.srv.cs.cmu.edu!crabapple.srv.cs.cmu.edu!bb3.andrew.cmu.edu!news.sei.cmu.edu!cis.ohio-state.edu!zaphod.mps.ohio-state.edu!darwin.sura.net!haven.umd.edu!decuac!pa.dec.com!e2big.mko.dec.com!nntpd.lkg.dec.com!ryn.mro4.dec.com!ricks.enet.dec.com!akhiani\nFrom: akhiani@ricks.enet.dec.com (Homayoon Akhiani)\nSubject: Re: Recommendations for removable storage media wanted\nMessage-ID: <1993Apr15.183133.25189@ryn.mro4.dec.com>\nLines: 25\nSender: news@ryn.mro4.dec.com (USENET News System)\nNntp-Posting-Host: ricks\nReply-To: akhiani@ricks.enet.dec.com (Homayoon Akhiani)\nOrganization: Digital Equipment Corporation\nX-Newsreader: mxrn 6.18-2\nReferences: <ls69u5INNo7g@nada.cs.utexas.edu> <1qf5qi$8d4@lll-winken.llnl.gov> <1993Apr14.115511.28278@kth.se>\nDate: Thu, 15 Apr 1993 18:31:33 GMT\n\n\nIn article <1993Apr14.115511.28278@kth.se> you write:\n|>>After having used both Syqyest and Bernoulli\'s, I most enthuiastically\n|>>recommend\n|

In [78]:
print('Model accuracy score: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score: 0.0000


In [77]:
y_pred_train = gnb.predict(X_train)
y_pred_train

array(["Newsgroups: talk.politics.mideast\nPath: cantaloupe.srv.cs.cmu.edu!crabapple.srv.cs.cmu.edu!bb3.andrew.cmu.edu!news.sei.cmu.edu!cis.ohio-state.edu!pacific.mps.ohio-state.edu!zaphod.mps.ohio-state.edu!howland.reston.ans.net!ux1.cso.uiuc.edu!news.cso.uiuc.edu!ux4.cso.uiuc.edu!eshneken\nFrom: eshneken@ux4.cso.uiuc.edu (Edward A Shnekendorf)\nSubject: Re: was: Go Hezbollah!!\nDate: Thu, 15 Apr 1993 16:19:21 GMT\nMessage-ID: <C5J9CA.8on@news.cso.uiuc.edu>\nReferences: <C5HuBA.CJo@news.cso.uiuc.edu> <1993Apr15.031349.21824@src.honeywell.com> <C5IFH7.3q4@news.cso.uiuc.edu> <1993Apr15.152619.12664@src.honeywell.com>\nSender: usenet@news.cso.uiuc.edu (Net Noise owner)\nOrganization: University of Illinois at Urbana\nLines: 45\n\namehdi@src.honeywell.com (Hossien Amehdi) writes:\n\n>In article <C5IFH7.3q4@news.cso.uiuc.edu> eshneken@ux4.cso.uiuc.edu (Edward A Shnekendorf) writes:\n>>\n>>What the hell do you know about Israeli policy?  What gives you the fiat\n>>to look into the minds of 

In [78]:
print('Training set score: {:.4f}'.format(gnb.score(X_train, y_train)))
print('Test set score: {:.4f}'.format(gnb.score(X_test, y_test)))

Training set score: 0.0143
Test set score: 0.0000


In [79]:
y_test.value_counts()

Path: cantaloupe.srv.cs.cmu.edu!crabapple.srv.cs.cmu.edu!fs7.ece.cmu.edu!europa.eng.gtefsd.com!zeus.ieee.org!fsbbs!p5.f175.n2240.z1.fidonet.org!Eric.Choi\nFrom: Eric.Choi@p5.f175.n2240.z1.fidonet.org (Eric Choi)\nSender: news\nNewsgroups: comp.sys.mac.hardware\nSubject: Re: HONGKONG\nMessage-ID: <27829.2BD029EC@zeus.ieee.org>\nDate: Fri, 16 Apr 93 21:02:46 EST\nOrganization: FidoNet node 1:2240/175.5 - Association Mac BBS, Grand Blanc MI\nLines: 25\n\n  ku> From: kinau@mondrian.CSUFresno.EDU (Kin Hung Au) Date: 13 Apr 93\n  ku> 07:22:05 GMT Organization: California State University, Fresno\n  ku> Message-ID: <C5Ev4t.G0A@zimmer.CSUFresno.EDU> Newsgroups:\n  ku> comp.sys.mac.hardware\n  ku> \n  ku> In Hong Kong , you can buy a cheap PC 386 or 486 based computer.\n  ku> However, it is very experience to buy a Macintosh. Last winter, I was\n  ku> back to Hong Kong. I saw the price of Mac Classic in Hong kong is same\n  ku> price to buy a LC in the U.S.\n  ku> \n  ku> I am not recommended t

In [81]:
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix\n\n', cm)
print('\nTrue Positives(TP) = ', cm[0,0])
print('\nTrue Negatives(TN) = ', cm[1,1])
print('\nFalse Positives(FP) = ', cm[0,1])
print('\nFalse Negatives(FN) = ', cm[1,0])

Confusion matrix

 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

True Positives(TP) =  0

True Negatives(TN) =  0

False Positives(FP) =  0

False Negatives(FN) =  0


In [79]:
print(classification_report(y_test, y_pred))

C:\Users\Admin\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Admin\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Admin\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(

In [82]:
TP = cm[0,0]
TN = cm[1,1]
FP = cm[0,1]
FN = cm[1,0]

In [83]:
precision = TP / float(TP + FP)
print('Precision : {0:0.4f}'.format(precision))

Precision : nan


C:\Users\Admin\AppData\Local\Temp\ipykernel_3792\1470815625.py:1: RuntimeWarning: invalid value encountered in divide
  precision = TP / float(TP + FP)


In [84]:
true_positive_rate = TP / float(TP + FN)
print('True Positive Rate : {0:0.4f}'.format(true_positive_rate))

True Positive Rate : nan


C:\Users\Admin\AppData\Local\Temp\ipykernel_3792\289249085.py:1: RuntimeWarning: invalid value encountered in divide
  true_positive_rate = TP / float(TP + FN)
